import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Next.js Tutorial - Codevolution', // fallback title for child elements that don't have a title
    template: '%s | Codevolution', // Adds a prefix / suffix.  Applies only to child elements.
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '10px' }}>
          <p>app header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'lightgrey', padding: '10px' }}>
          <p>app footer</p>
        </footer>
      </body>
    </html>
  );
}
